# Generated by Django 3.0.6 on 2020-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('degere', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=250)),
            ],
        ),
    ]
